# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\x1a\x1egoogle/protobuf/wrappers.proto\"\"\n\nAddRequest\x12\t\n\x01\x61\x18\x01 \x01(\x01\x12\t\n\x01\x62\x18\x02 \x01(\x01\"\x17\n\x08\x41\x64\x64Reply\x12\x0b\n\x03sum\x18\x01 \x01(\x01\"}\n\rRandomRequest\x12-\n\x03min\x18\x01 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueH\x00\x88\x01\x01\x12-\n\x03max\x18\x02 \x01(\x0b\x32\x1b.google.protobuf.Int32ValueH\x01\x88\x01\x01\x42\x06\n\x04_minB\x06\n\x04_max\"\x1d\n\x0bRandomReply\x12\x0e\n\x06result\x18\x01 \x01(\x05\x32\x7f\n\nCalculator\x12\x33\n\x03\x41\x64\x64\x12\x16.calculator.AddRequest\x1a\x14.calculator.AddReply\x12<\n\x06Random\x12\x19.calculator.RandomRequest\x1a\x17.calculator.RandomReplyB\x0e\xaa\x02\x0bGrpcServiceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\013GrpcService'
  _ADDREQUEST._serialized_start=64
  _ADDREQUEST._serialized_end=98
  _ADDREPLY._serialized_start=100
  _ADDREPLY._serialized_end=123
  _RANDOMREQUEST._serialized_start=125
  _RANDOMREQUEST._serialized_end=250
  _RANDOMREPLY._serialized_start=252
  _RANDOMREPLY._serialized_end=281
  _CALCULATOR._serialized_start=283
  _CALCULATOR._serialized_end=410
# @@protoc_insertion_point(module_scope)
